# Generated by Django 2.1.1 on 2021-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210121_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='section',
            field=models.CharField(default='Frutas y Verduras', max_length=300),
            preserve_default=False,
        ),
    ]
