# Generated by Django 2.1.1 on 2021-01-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ingredient_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.CharField(default='Breakfast', max_length=200),
            preserve_default=False,
        ),
    ]
